apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - './infra/k8s/*'
build:
  local:
    push: false
  artifacts:
    - image: 'm7md9078/blog-app-client'
      context: 'client'
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: 'm7md9078/blog-app-posts-service'
      context: './services/posts'
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: 'm7md9078/blog-app-comments-service'
      context: './services/comments'
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: 'm7md9078/blog-app-query-service'
      context: './services/query'
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: 'm7md9078/blog-app-event-bus-service'
      context: './services/event-bus'
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
